name: Org Terraform Validate
on:
    pull_request:
      paths:
        - '**.tf'
      branches:
        - main
    workflow_call:

jobs:
  validate-terraform:
    uses: Coalfire-CF/Actions/.github/workflows/org-terraform-validate.yml@main